name: 'Block merge labeler'
description: 'If release PR has an `block merge` label, puts this label to all other PRs to master'
inputs:
  label:
    description: 'Label name'
    required: true
    default: 'block merge'
  release-source-branch:
    description: 'Develop branch name'
    required: true
    default: 'develop'
runs:
  using: 'node16'
  main: 'dist/index.js'
